const requiredEnvVar = [
  "PORT",
  "ACCESSTOKEN",
  "ACCESSEXPIRE",
  "REFRESHTOKEN",
  "REFRESHEXPIRE",
  "MONGO_URL",
  "NODEMAILER_PASS",
  "NODEMAILER_USER",
  "STRIPE_SECRET_KEY",
  "CLOUDINARY_CLOUD_NAME",
  "CLOUDINARY_API_KEY",
  "CLOUDINARY_API_SECRET",
  "STRIPE_SECRET_KEY",
];

